apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: petclinic-qa
stringData:
  database-name: petclinic
  database-password: petclinic
  database-root-password: petclinic
  database-user: petclinic
  